---
title: "Unsupervised and semisupervised learning for incomplete data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{unsupMI_semisup_cox}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
require(markdown)
```

# Unsupervised learning
```{r setup}
library(doMIsaul)
## With imputation included TO DO
data(cancer, package = "survival")
cancer$status <- cancer$status - 1
res.0 <- unsupMI(data = list(cancer), Impute = "MImpute_surv",
                 cleanup.partition = FALSE)

### With imputation not included
## 1 imputation
cancer.imp <- MImpute_surv(cancer, 3)
## 2 learning
res <- unsupMI(data = cancer.imp, cleanup.partition = FALSE)
summary(factor(res))
res.1 <- unsupMI(data = cancer.imp)
summary(factor(res.1))

## 2.bis learning with several algorithms
res.2 <- unsupMI(data = cancer.imp, algo = c("km", "hc"), comb.cons = TRUE,
                 plot.cons = TRUE)

## Alternative: perform imputation within
res <- unsupMI(Impute = "MImpute_surv", data = list(cancer))

```
